mobac.revision.fallback=$Revision$
mobac.revision.hide=false
mobac.updateurl=https://mobac.sourceforge.io/mapsources-update/v3/mappacks-md5.txt
mobac.updatebaseurl=https://mobac.sourceforge.io/mapsources-update/v3/
mobac.mappackversion=1