plugins {
    id 'java'
}

dependencies {
    implementation project(':mobac')
    implementation project(':mappacks:openstreetmap')
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}

test {
    useJUnitPlatform()
}
jar{
    archiveFileName = "MapEvaluator.jar"
    manifest {
        attributes "Main-Class": "mobac.StartMapEvaluator"
        attributes "Class-Path": "Mobile_Atlas_Creator.jar"
    }
}